[package]
name = "lightspeed_cash_credit_tally"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.22"
serde = "1.0.193"
tokio = "1.35.0"
